// packages/react-instantsearch-dom/src/components/Pagination.js
import { range } from 'lodash';
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { translatable } from 'react-instantsearch-core';
import { createClassNames, capitalize } from '../core/utils';
import LinkList from './LinkList';

const cx = createClassNames('Pagination');

// Determines the size of the widget (the number of pages displayed - that the user can directly click on)
function calculateSize(padding, maxPages) {
  return Math.min(2 * padding + 1, maxPages);
}

function calculatePaddingLeft(currentPage, padding, maxPages, size) {
  if (currentPage <= padding) {
    return currentPage;
  }

  if (currentPage >= maxPages - padding) {
    return size - (maxPages - currentPage);
  }

  return padding + 1;
}

// Retrieve the correct page range to populate the widget
function getPages(currentPage, maxPages, padding) {
  const size = calculateSize(padding, maxPages);
  // If the widget size is equal to the max number of pages, return the entire page range
  if (size === maxPages) return range(1, maxPages + 1);

  const paddingLeft = calculatePaddingLeft(
    currentPage,
    padding,
    maxPages,
    size
  );
  const paddingRight = size - paddingLeft;

  const first = currentPage - paddingLeft;
  const last = currentPage + paddingRight;
  return range(first + 1, last + 1);
}

class Pagination extends Component {
  static propTypes = {
    nbPages: PropTypes.number.isRequired,
    currentRefinement: PropTypes.number.isRequired,
    refine: PropTypes.func.isRequired,
    createURL: PropTypes.func.isRequired,
    canRefine: PropTypes.bool.isRequired,

    translate: PropTypes.func.isRequired,
    listComponent: PropTypes.func,

    showFirst: PropTypes.bool,
    showPrevious: PropTypes.bool,
    showNext: PropTypes.bool,
    showLast: PropTypes.bool,
    padding: PropTypes.number,
    totalPages: PropTypes.number,
    className: PropTypes.string,
  };

  static defaultProps = {
    listComponent: LinkList,
    showFirst: true,
    showPrevious: true,
    showNext: true,
    showLast: false,
    padding: 3,
    totalPages: Infinity,
    className: '',
  };

  getItem(modifier, translationKey, value) {
    const { nbPages, totalPages, translate } = this.props;
    return {
      key: `${modifier}.${value}`,
      modifier,
      disabled: value < 1 || value >= Math.min(totalPages, nbPages),
      label: translate(translationKey, value),
      value,
      ariaLabel: translate(`aria${capitalize(translationKey)}`, value),
    };
  }

  render() {
    const {
      listComponent: ListComponent,
      nbPages,
      totalPages,
      currentRefinement,
      padding,
      showFirst,
      showPrevious,
      showNext,
      showLast,
      refine,
      createURL,
      canRefine,
      translate,
      className,
      ...otherProps
    } = this.props;

    const maxPages = Math.min(nbPages, totalPages);
    const lastPage = maxPages;

    let items = [];
    if (showFirst) {
      items.push({
        key: 'first',
        modifier: 'item--firstPage',
        disabled: currentRefinement === 1,
        label: translate('first'),
        value: 1,
        ariaLabel: translate('ariaFirst'),
      });
    }
    if (showPrevious) {
      items.push({
        key: 'previous',
        modifier: 'item--previousPage',
        disabled: currentRefinement === 1,
        label: translate('previous'),
        value: currentRefinement - 1,
        ariaLabel: translate('ariaPrevious'),
      });
    }

    items = items.concat(
      getPages(currentRefinement, maxPages, padding).map(value => ({
        key: value,
        modifier: 'item--page',
        label: translate('page', value),
        value,
        selected: value === currentRefinement,
        ariaLabel: translate('ariaPage', value),
      }))
    );
    if (showNext) {
      items.push({
        key: 'next',
        modifier: 'item--nextPage',
        disabled: currentRefinement === lastPage || lastPage <= 1,
        label: translate('next'),
        value: currentRefinement + 1,
        ariaLabel: translate('ariaNext'),
      });
    }
    if (showLast) {
      items.push({
        key: 'last',
        modifier: 'item--lastPage',
        disabled: currentRefinement === lastPage || lastPage <= 1,
        label: translate('last'),
        value: lastPage,
        ariaLabel: translate('ariaLast'),
      });
    }

    return (
      <div
        className={classNames(cx('', !canRefine && '-noRefinement'), className)}
      >
        <ListComponent
          {...otherProps}
          cx={cx}
          items={items}
          onSelect={refine}
          createURL={createURL}
          canRefine={canRefine}
        />
      </div>
    );
  }
}

export default translatable({
  previous: '‹',
  next: '›',
  first: '«',
  last: '»',
  page: currentRefinement => currentRefinement.toString(),
  ariaPrevious: 'Previous page',
  ariaNext: 'Next page',
  ariaFirst: 'First page',
  ariaLast: 'Last page',
  ariaPage: currentRefinement => `Page ${currentRefinement.toString()}`,
})(Pagination);

// packages/vue-instantsearch/src/components/Pagination.vue
<template>
  <div :class="suit()" v-if="state">
    <slot
      :refine="refine"
      :createURL="state.createURL"
      :currentRefinement="state.currentRefinement"
      :nbHits="state.nbHits"
      :nbPages="state.nbPages"
      :pages="state.pages"
      :isFirstPage="state.isFirstPage"
      :isLastPage="state.isLastPage"
    >
      <ul :class="suit('list')">
        <li
          :class="{
            [suit('item')]:true,
            [suit('item', 'firstPage')]: true,
            [suit('item', 'disabled')]: state.isFirstPage
          }"
        >
          <template v-if="!state.isFirstPage">
            <a
              :class="suit('link')"
              aria-label="First"
              :href="state.createURL(0)"
              @click.prevent="refine(0)"
            >‹‹</a>
          </template>
          <template v-else>
            <span :class="suit('link')" aria-label="Previous">‹‹</span>
          </template>
        </li>
        <li
          :class="{
            [suit('item')]: true,
            [suit('item', 'previousPage')]: true,
            [suit('item', 'disabled')]: state.isFirstPage
          }"
        >
          <template v-if="!state.isFirstPage">
            <a
              :class="suit('link')"
              aria-label="Previous"
              :href="state.createURL(state.currentRefinement - 1)"
              @click.prevent="refine(state.currentRefinement - 1)"
            >‹</a>
          </template>
          <template v-else>
            <span :class="suit('link')" aria-label="Previous">‹</span>
          </template>
        </li>

        <li
          :class="{
            [suit('item')]:true,
            [suit('item', 'selected')]: state.currentRefinement === page
          }"
          v-for="page in state.pages" :key="page"
        >
          <a
            :class="suit('link')"
            :href="state.createURL(page)"
            @click.prevent="refine(page)"
          >
            {{page + 1}}
          </a>
        </li>

        <li
          :class="{
            [suit('item')]:true,
            [suit('item','nextPage')]: true,
            [suit('item','disabled')]: state.isLastPage
          }"
        >
          <template v-if="!state.isLastPage">
            <a
              :class="suit('link')"
              aria-label="Next"
              :href="state.createURL(state.currentRefinement + 1)"
              @click.prevent="refine(state.currentRefinement + 1)"
            >›</a>
          </template>
          <template v-else>
            <span :class="suit('link')" aria-label="Next">›</span>
          </template>
        </li>
        <li
          :class="{
            [suit('item')]:true,
            [suit('item','lastPage')]: true,
            [suit('item','disabled')]: state.isLastPage
          }"
        >
          <template v-if="!state.isLastPage">
            <a
              :class="suit('link')"
              aria-label="Last"
              :href="state.createURL(state.nbPages - 1)"
              @click.prevent="refine(state.nbPages - 1)"
            >››</a>
          </template>
          <template v-else>
            <span :class="suit('link')" aria-label="Last">››</span>
          </template>
        </li>
      </ul>
    </slot>
  </div>
</template>

<script>
import algoliaComponent from '../component';
import { connectPagination } from 'instantsearch.js/es/connectors';

export default {
  mixins: [algoliaComponent],
  props: {
    padding: {
      type: Number,
      default: 3,
      validator(value) {
        return value > 0;
      },
    },
    totalPages: {
      type: Number,
      validator(value) {
        return value > 0;
      },
    },
    showFirst: {
      type: Boolean,
      default: true,
    },
    showLast: {
      type: Boolean,
      default: true,
    },
    showNext: {
      type: Boolean,
      default: true,
    },
    showPrevious: {
      type: Boolean,
      default: true,
    },
  },
  data() {
    return {
      widgetName: 'Pagination',
    };
  },
  beforeCreate() {
    this.connector = connectPagination;
  },
  computed: {
    widgetParams() {
      return {
        padding: this.padding,
        maxPages: this.totalPages,
      };
    },
  },
  methods: {
    refine(page) {
      const p = Math.min(Math.max(page, 0), this.state.nbPages - 1);
      this.state.refine(p);
      // @TODO: do this in a general way
      this.$emit('page-change', p);
    },
  },
};</script>
