// examples/hooks/default-theme/components/RangeInput.tsx
import React, { useEffect, useState } from 'react';

import { useRange, UseRangeProps } from 'react-instantsearch-hooks';
import { cx } from '../cx';

export type RangeProps = React.ComponentProps<'div'> & UseRangeProps;

// if the default value is undefined, React considers the component uncontrolled initially, which we don't want 0 or NaN as the default value
const unsetNumberInputValue = '' as unknown as number;

export function RangeInput(props: RangeProps) {
  const {
    range: { min, max },
    start: [minValue, maxValue],
    canRefine,
    refine,
  } = useRange(props);
  const values = {
    min:
      minValue !== -Infinity && minValue !== min
        ? minValue
        : unsetNumberInputValue,
    max:
      maxValue !== Infinity && maxValue !== max
        ? maxValue
        : unsetNumberInputValue,
  };
  const [{ from, to }, setRange] = useState({
    from: values.min,
    to: values.max,
  });

  useEffect(() => {
    setRange({ from: values.min, to: values.max });
  }, [values.min, values.max]);

  return (
    <div
      className={cx(
        'ais-RangeInput',
        !canRefine && 'ais-RangeInput-noRefinement',
        props.className
      )}
    >
      <form
        className="ais-RangeInput-form"
        onSubmit={(event) => {
          event.preventDefault();
          refine([from, to]);
        }}
      >
        <input
          className="ais-RangeInput-input ais-RangeInput-input--min"
          type="number"
          min={min}
          max={max}
          value={from}
          placeholder={min ? min.toString() : ''}
          disabled={!canRefine}
          onChange={(event) =>
            setRange({ from: Number(event.currentTarget.value), to })
          }
        />
        <span className="ais-RangeInput-separator"> - </span>
        <input
          className="ais-RangeInput-input ais-RangeInput-input--max"
          type="number"
          min={min}
          max={max}
          value={to}
          placeholder={max ? max.toString() : ''}
          disabled={!canRefine}
          onChange={(event) =>
            setRange({ from, to: Number(event.currentTarget.value) })
          }
        />
        <button className="ais-RangeInput-submit" type="submit">
          Go
        </button>
      </form>
    </div>
  );
}

// packages/vue-instantsearch/src/components/RangeInput.vue
<template>
  <div
    v-if="state"
    :class="[suit(), !canRefine && suit('', 'noRefinement')]"
  >
    <slot
      :currentRefinements="state.start"
      :refine="refine"
      :can-refine="canRefine"
      :range="state.range"
    >
      <form
        :class="suit('form')"
        @submit.prevent="refine(minInput, maxInput)"
      >
        <label :class="suit('label')">
          <slot name="minLabel" />
          <input
            type="number"
            :class="[suit('input'), suit('input', 'min')]"
            :step="step"
            :min="state.range.min"
            :max="state.range.max"
            :placeholder="state.range.min"
            :value="values.min"
            @change="minInput = $event.currentTarget.value"
          >
        </label>
        <span :class="suit('separator')">
          <slot name="separator">to</slot>
        </span>
        <label :class="suit('label')">
          <slot name="maxLabel" />
          <input
            :class="[suit('input'), suit('input', 'max')]"
            type="number"
            :step="step"
            :min="state.range.min"
            :max="state.range.max"
            :placeholder="state.range.max"
            :value="values.max"
            @change="maxInput = $event.currentTarget.value"
          >
        </label>
        <button
          :class="suit('submit')"
          type="submit"
        >
          <slot name="submitLabel">Go</slot>
        </button>
      </form>
    </slot>
  </div>
</template>

<script>
import { connectRange } from 'instantsearch.js/es/connectors';
import { createWidgetMixin } from '../mixins/widget';
import { createPanelConsumerMixin } from '../mixins/panel';
import { createSuitMixin } from '../mixins/suit';

const mapStateToCanRefine = state =>
  state && state.range && state.range.min !== state.range.max;

export default {
  mixins: [
    createSuitMixin({ name: 'RangeInput' }),
    createWidgetMixin({ connector: connectRange }),
    createPanelConsumerMixin({
      mapStateToCanRefine,
    }),
  ],
  props: {
    attribute: {
      type: String,
      required: true,
    },
    min: {
      type: Number,
      required: false,
      default: -Infinity,
    },
    max: {
      type: Number,
      required: false,
      default: Infinity,
    },
    precision: {
      type: Number,
      required: false,
      default: 0,
    },
  },
  data() {
    return {
      minInput: undefined,
      maxInput: undefined,
    };
  },
  computed: {
    widgetParams() {
      return {
        attributeName: this.attribute,
        min: this.min,
        max: this.max,
        precision: this.precision,
      };
    },
    canRefine() {
      return mapStateToCanRefine(this.state);
    },
    step() {
      return 1 / Math.pow(10, this.precision);
    },
    values() {
      const [minValue, maxValue] = this.state.start;
      const { min: minRange, max: maxRange } = this.state.range;

      return {
        min: minValue !== -Infinity && minValue !== minRange ? minValue : null,
        max: maxValue !== Infinity && maxValue !== maxRange ? maxValue : null,
      };
    },
  },
  methods: {
    refine(min, max) {
      this.state.refine([min, max]);
    },
  },
};
</script>
