// packages/vue-instantsearch/src/components/Panel.vue
<template>
  <div :class="[suit(), !canRefine && suit('', 'noRefinement')]">
    <div
      v-if="$slots.header"
      :class="suit('header')"
    >
      <slot name="header" />
    </div>
    <div class="ais-Panel-body">
      <slot />
    </div>
    <div
      v-if="$slots.footer"
      :class="suit('footer')"
    >
      <slot name="footer" />
    </div>
  </div>
</template>

<script>
import { createPanelProviderMixin } from '../mixins/panel';
import { createSuitMixin } from '../mixins/suit';

export default {
  name: 'AisPanel',
  mixins: [createSuitMixin({ name: 'Panel' }), createPanelProviderMixin()],
};
</script>

// examples/react/css/src/Panel.tsx
import React from 'react';

type PanelProps = React.PropsWithChildren<{
  header: string;
  footer?: React.ReactNode;
}>;

export function Panel({ header, children, footer }: PanelProps) {
  return (
    <div className="ais-Panel">
      <div className="ais-Panel-header">
        <span>{header}</span>
      </div>
      <div className="ais-Panel-body">{children}</div>
      <div className="ais-Panel-footer">{footer}</div>
    </div>
  );
}
