// angular-instantsearch/src/app/app.component.ts
import { Component } from '@angular/core';
import algoliasearch from 'algoliasearch/lite';

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  config = {
    indexName: 'instant_search',
    searchClient,
  };
}

<header class="header">
  <h1 class="header-title">
    <a href="/">angular-instantsearch-app</a>
  </h1>
  <p class="header-subtitle">
    using
    <a href="https://github.com/algolia/angular-instantsearch">
      Angular InstantSearch
    </a>
  </p>
</header>

<div class="container">
  <ais-instantsearch [config]="config">
    <ais-configure [searchParameters]="{ hitsPerPage: 8 }"></ais-configure>
    <div class="search-panel">
      <div class="search-panel__filters">
        <ais-panel header="brand">
          <ais-refinement-list attribute="brand"></ais-refinement-list>
        </ais-panel>
      </div>

      <div class="search-panel__results">
        <div class="searchbox">
          <ais-search-box placeholder=""></ais-search-box>
        </div>

        <ais-hits>
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.length === 0">
              No results found matching <strong></strong>.
            </div>

            <ol class="ais-Hits-list">
              <li class="ais-Hits-item" *ngFor="let hit of hits">
                <article>
                  <h1>
                    <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
                  </h1>

                  <p>
                    <ais-highlight attribute="description" [hit]="hit"></ais-highlight>
                  </p>
                </article>
              </li>
            </ol>
          </ng-template>
        </ais-hits>

        <div class="pagination">
          <ais-pagination></ais-pagination>
        </div>
      </div>

    </div>
  </ais-instantsearch>
</div>

// examples/react/getting-started/src/App.js
import algoliasearch from 'algoliasearch/lite';
import React from 'react';
import {
  InstantSearch,
  Configure,
  Hits,
  SearchBox,
  Panel,
  RefinementList,
  Pagination,
  Highlight,
} from 'react-instantsearch-dom';
import './App.css';

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

function App() {
  return (
    <div>
      <header className="header">
        <h1 className="header-title">
          <a href="/">Getting started</a>
        </h1>
        <p className="header-subtitle">
          using{' '}
          <a href="https://github.com/algolia/instantsearch/tree/master/packages/react-instantsearch-dom">
            React InstantSearch
          </a>
        </p>
      </header>

      <div className="container">
        <InstantSearch searchClient={searchClient} indexName="instant_search">
          <Configure hitsPerPage={8} />
          <div className="search-panel">
            <div className="search-panel__filters">
              <Panel header="brand">
                <RefinementList attribute="brand" />
              </Panel>
            </div>

            <div className="search-panel__results">
              <SearchBox
                className="searchbox"
                translations={{
                  placeholder: '',
                }}
              />
              <Hits hitComponent={Hit} />

              <div className="pagination">
                <Pagination />
              </div>
            </div>
          </div>
        </InstantSearch>
      </div>
    </div>
  );
}

function Hit(props) {
  return (
    <article>
      <h1>
        <Highlight attribute="name" hit={props.hit} />
      </h1>
      <p>
        <Highlight attribute="description" hit={props.hit} />
      </p>
    </article>
  );
}

export default App;
