// packages/vue-instantsearch/src/components/NumericMenu.vue
<template>
  <div
    v-if="state"
    :class="[suit(), !state.canRefine && suit('', 'noRefinement')]"
  >
    <slot
      :items="state.items"
      :can-refine="state.canRefine"
      :refine="state.refine"
      :createURL="state.createURL"
      :send-event="state.sendEvent"
    >
      <ul :class="[suit('list')]">
        <li
          v-for="item in state.items"
          :key="item.label"
          :class="[suit('item'), item.isRefined && suit('item', 'selected')]"
        >
          <label :class="suit('label')">
            <input
              type="radio"
              :class="suit('radio')"
              :name="attribute"
              :value="item.value"
              :checked="item.isRefined"
              @change="state.refine($event.target.value)"
            >
            <span :class="suit('labelText')">{{ item.label }}</span>
          </label>
        </li>
      </ul>
    </slot>
  </div>
</template>

<script>
import { connectNumericMenu } from 'instantsearch.js/es/connectors';
import { createPanelConsumerMixin } from '../mixins/panel';
import { createWidgetMixin } from '../mixins/widget';
import { createSuitMixin } from '../mixins/suit';

export default {
  name: 'AisNumericMenu',
  mixins: [
    createWidgetMixin(
      {
        connector: connectNumericMenu,
      },
      {
        $$widgetType: 'ais.numericMenu',
      }
    ),
    createSuitMixin({ name: 'NumericMenu' }),
    createPanelConsumerMixin(),
  ],
  props: {
    attribute: {
      type: String,
      required: true,
    },
    items: {
      type: Array,
      required: true,
    },
    transformItems: {
      type: Function,
      default: undefined,
    },
  },
  computed: {
    widgetParams() {
      return {
        attribute: this.attribute,
        transformItems: this.transformItems,
        items: this.items,
      };
    },
  },
};
</script>

// packages/react-instantsearch/src/ui/NumericMenu.tsx
import { cx } from 'instantsearch-ui-components';
import React from 'react';

import type { NumericMenuRenderStateItem } from 'instantsearch.js/es/connectors/numeric-menu/connectNumericMenu';

export type NumericMenuProps = Omit<React.ComponentProps<'div'>, 'onChange'> & {
  items: NumericMenuRenderStateItem[];
  attribute: string;
  onRefine: (value: string) => void;
  classNames?: Partial<NumericMenuClassNames>;
};

export type NumericMenuClassNames = {
  /**
   * Class names to apply to the root element
   */
  root: string;
  /**
   * Class names to apply to the root element when there are no refinements possible
   */
  noRefinementRoot: string;
  /**
   * Class names to apply to the list element
   */
  list: string;
  /**
   * Class names to apply to each item element
   */
  item: string;
  /**
   * Class names to apply to each selected item element
   */
  selectedItem: string;
  /**
   * Class names to apply to each label element
   */
  label: string;
  /**
   * Class names to apply to each radio input element
   */
  radio: string;
  /**
   * Class names to apply to each label text element
   */
  labelText: string;
};

export function NumericMenu({
  items,
  attribute,
  onRefine,
  classNames = {},
  ...props
}: NumericMenuProps) {
  return (
    <div
      {...props}
      className={cx(
        'ais-NumericMenu',
        classNames.root,
        items.length === 0 &&
          cx('ais-NumericMenu--noRefinement', classNames.noRefinementRoot),
        props.className
      )}
    >
      <ul className={cx('ais-NumericMenu-list', classNames.list)}>
        {items.map((item) => (
          <li
            key={item.value}
            className={cx(
              'ais-NumericMenu-item',
              classNames.item,
              item.isRefined &&
                cx('ais-NumericMenu-item--selected', classNames.selectedItem)
            )}
          >
            <label className={cx('ais-NumericMenu-label', classNames.label)}>
              <input
                className={cx('ais-NumericMenu-radio', classNames.radio)}
                type="radio"
                name={attribute}
                value={item.value}
                checked={item.isRefined}
                onChange={(event) => onRefine(event.target.value)}
              />
              <span
                className={cx(
                  'ais-NumericMenu-labelText',
                  classNames.labelText
                )}
              >
                {item.label}
              </span>
            </label>
          </li>
        ))}
      </ul>
    </div>
  );
}
